### ISSUE TITLE
Plan 9 support

### ISSUE THREAD

**Issue by nietzschitel** [takada07/QOnScreenKeyboard#2]
Please provide support for Plan 9.

**Comment by takada07** [comment]
Do you have working QT5 and PyQt5 build for Plan 9? I'm not familiar with this OS but sure, if you can send me some tutorials how to make it working, I can play little bit with that.

Basically nothing strange is there, if QT5 is runing, you can build at least C++ bindings. (just run qmake -qt5 in src directory as is written in README.md). If you succeed with that, let me know, I will continue on python bindings. Otherwise I will close this issue.

**Comment by nietzschitel** [comment]
Looks like Qt5 is not supported on Plan 9. :-(
You can close the issue.
